apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - application-service-monitor.yaml
  - cluster-metrics-servicemonitor.yaml
  - kafka-podmonitors.yaml
  - operator-service-monitor.yaml
