- op: add
  path: /metadata/annotations
  value:
    service.alpha.openshift.io/serving-cert-secret-name: modelmesh-proxy-tls
- op: replace
  path: /spec/ports/0/targetPort
  value: 8008
- op: replace
  path: /spec/ports/0/port
  value: 8008
